// Titles and meta descriptions from the audit of Thursday 24 September 2026.
// Head tags only - the words on the pages are untouched. Every line is 50-60
// characters (titles) or 140-160 (descriptions), built from facts on the page.
export const seoMeta: Record<string, { title: string; description: string }> = {
  "/services/": { title: "Provo SEO and Local Marketing Services | Provo SEO Pros", description: "Local SEO, Google Business Profile, AI search, websites, CRM follow-up and Google Ads from a Provo, Utah SEO company. Starting prices listed on every service." },
  "/about/": { title: "About Rich Soto, Provo SEO Since 2001 | Provo SEO Pros", description: "Rich Soto started Provo SEO Pros in 2001 to help local businesses get found. You work directly with the founder, with scope and terms confirmed in writing." },
  "/contact/": { title: "Contact Our Provo, Utah SEO Company | Provo SEO Pros", description: "Call +1 866-402-6849, email contact@provoseopros.com or book a free Growth Audit with Provo SEO Pros in Provo, Utah. Monday to Friday, 9am to 5pm MT." },
  "/book-a-growth-audit/": { title: "Book a Free 30-Minute SEO Growth Audit | Provo SEO Pros", description: "Book a free 30-minute Growth Audit. We review your website, Google Business Profile and local search presence, and reply within one business day." },
  "/pricing/": { title: "Provo SEO Pricing and Starting Prices | Provo SEO Pros", description: "Starting prices for local SEO, Google Business Profile, AI search, websites, CRM follow-up and Google Ads. Scope and terms confirmed in writing first." },
  "/blog/": { title: "Local SEO and AI Search Advice Blog | Provo SEO Pros", description: "Plain-English advice on local SEO, Google Business Profile, AI search and lead follow-up for local business owners, from Provo SEO Pros founder Rich Soto." },
  "/service/website-design-conversion-optimization/": { title: "Website Design & Conversion Optimization | Provo SEO Pros", description: "Websites, landing pages, forms and calls to action built so more visitors to your service business call, book or send an inquiry. From $3,500." },
  "/service/social-media-management/": { title: "Local Social Media Management Services | Provo SEO Pros", description: "Consistent, on-brand social media posts that show your work, reviews and expertise, so people checking out your local business see it is active. From $750/mo." },
  "/service/ppc-advertising-management/": { title: "Google Ads and PPC Management Services | Provo SEO Pros", description: "Google Ads campaigns built around your highest-value services, with focused landing pages, call and form tracking, and regular optimization. From $750/mo." },
  "/service/technical-optimization-site-speed-utah/": { title: "Technical SEO and Site Speed Optimization | Provo SEO Pros", description: "Faster pages, better Core Web Vitals, clean crawling and indexing, and fixed broken links, so Google and your visitors can use your website without friction." },
  "/service/missed-call-text-back-med-spas/": { title: "Missed Call Text Back for Med Spas | Provo SEO Pros", description: "When a caller misses your med spa, they get an instant text with a booking link, and your staff get notified, so fewer missed calls turn into lost clients." },
  "/service/ai-seo/": { title: "AI SEO Services for Local Businesses | Provo SEO Pros", description: "Help AI search tools and answer engines understand, summarize and recommend your business, with clear service pages, structured data and answer-ready FAQs." },
  "/service/growth-engine/": { title: "Growth Engine System for Local Businesses | Provo SEO Pros", description: "One coordinated system for local SEO, AI search, your website, Google Business Profile, reviews, campaigns and tracking. Three ways to start, from $2,500." },
  "/service/seo-ai-search-optimization/": { title: "Provo SEO Services & AI Search Optimization | Provo SEO Pros", description: "SEO services from a Provo, Utah company: clearer service pages, stronger local relevance and a sound site, so Google, Maps and AI search can find you." },
  "/service/google-business-profile-management/": { title: "Google Business Profile Management | Provo SEO Pros", description: "A complete, accurate Google Business Profile with the right categories, services, reviews and contact paths, so local searchers pick you. From $900/mo." },
  "/service/crm-automation/": { title: "CRM Automation and Lead Follow-Up | Provo SEO Pros", description: "Automated lead capture, instant text and email replies, missed-call text-back and follow-up sequences, so no new inquiry slips through the cracks." },
  "/local-visibility-blueprint/": { title: "Local SEO Plan: Local Visibility Blueprint™ | Provo SEO Pros", description: "A focused diagnosis and prioritized roadmap for local visibility, website conversion and your Google Business Profile. One-time, starting at $2,500." },
  "/local-authority-guided-implementation/": { title: "Guided Implementation™ Local SEO Buildout | Provo SEO Pros", description: "A focused 90-day, done-with-you buildout of your local SEO, Google Business Profile, service pages and website conversion. From $7,500 + $2,500/mo." },
  "/local-authority-managed-growth/": { title: "Local Authority Managed Growth™ Managed SEO | Provo SEO Pros", description: "Done-for-you local SEO, website conversion, Google Business Profile and reputation work, led by a focused partner. From $15,000 + $4,500/mo." },
  "/what-is-a-growth-engine-system/": { title: "What Is a Growth Engine System for Local Businesses?", description: "Most local businesses don't have a marketing problem, they have a systems problem. Here's how a Growth Engine System connects your website, SEO and follow-up." },
  "/seo-vs-ai-seo/": { title: "SEO vs AI SEO: What Local Business Owners Need to Know", description: "Traditional SEO helps you rank. AI SEO helps Google AI Overviews, ChatGPT and Perplexity understand and recommend you. Here's how they work together." },
  "/website-traffic-but-no-leads/": { title: "Why Your Website Gets Traffic But Not Leads | Provo SEO Pros", description: "Visitors browse, then leave without calling or booking. The problem is usually conversion, not traffic. Here's what to check and fix on your website." },
  "/crm-automation-follow-up/": { title: "How CRM Automation Helps Local Businesses Follow Up Faster", description: "Most local businesses lose leads to slow, inconsistent follow-up, not lack of interest. Here's how CRM automation helps you reply faster and keep track." },
};
